FROM node:20-slim AS base
ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"
RUN corepack enable && corepack prepare pnpm@10.30.1 --activate
WORKDIR /app

FROM base AS build
COPY package.json .
COPY package-lock.json .
RUN pnpm import
RUN --mount=type=cache,id=pnpm,target=/pnpm/store pnpm install --frozen-lockfile
COPY . .
RUN pnpm run build

FROM busybox:stable
WORKDIR /www
COPY --from=build /app/dist .
EXPOSE 5173
CMD ["httpd", "-f", "-v", "-p", "5173"]

