// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/auth/login": {
            "post": {
                "description": "Verify user’s login credentials (username and password), then generate a session and return the session token back to user",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "/auth"
                ],
                "summary": "login",
                "parameters": [
                    {
                        "description": "login parameters",
                        "name": "Request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/auth.LoginParam"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Ok",
                        "schema": {
                            "$ref": "#/definitions/auth.LoginResponse"
                        }
                    },
                    "404": {
                        "description": "User not found in db",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "409": {
                        "description": "Invalid Credentials",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/auth/logout": {
            "get": {
                "description": "Verify the received token and perform session clean up.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "/auth"
                ],
                "summary": "logout",
                "parameters": [
                    {
                        "type": "string",
                        "example": "f3d9c4e6a7b1ce204fa8d5b39e181f9b3e2c1d7fbe4490d6732eab5c4fd7c92e",
                        "description": "256bit random token",
                        "name": "Token",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    }
                }
            }
        },
        "/auth/signup": {
            "post": {
                "description": "Receive the sign up information, validate username (check if it exists), password (has to be lower than 71 byte for bcrypt hashing), and email (correct format). Then generate the session and return the token to the user (auto login)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "/auth"
                ],
                "summary": "signup",
                "parameters": [
                    {
                        "description": "signup parameters",
                        "name": "Request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/auth.SignupParam"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Account Created",
                        "schema": {
                            "$ref": "#/definitions/auth.SignupResponse"
                        }
                    },
                    "409": {
                        "description": "Password too long (over 71 bytes)",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/dishes/search": {
            "get": {
                "description": "Search dishes by name, course list, and ingredient count range. Results are paginated and include total match count.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "/dishes"
                ],
                "summary": "Search dishes with filters and pagination",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Search query for dish name",
                        "name": "q",
                        "in": "query"
                    },
                    {
                        "type": "array",
                        "items": {
                            "type": "string"
                        },
                        "collectionFormat": "csv",
                        "description": "Filter by course (can be repeated)",
                        "name": "course",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Minimum number of ingredients",
                        "name": "min_ingredients",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Maximum number of ingredients",
                        "name": "max_ingredients",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Number of results per page (default: 12)",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Page number (1-based)",
                        "name": "page",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Search results",
                        "schema": {
                            "$ref": "#/definitions/handlers.SearchDishesResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid query parameters",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/users/favorites": {
            "get": {
                "description": "Get the user id from the received session token, then query and return the list of user’s favorite dishes.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "/users/favorites"
                ],
                "summary": "get_info",
                "parameters": [
                    {
                        "type": "string",
                        "description": "256bit random token",
                        "name": "Token",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Ok",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/handlers.Favorites"
                            }
                        }
                    },
                    "401": {
                        "description": "no auth token found",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "403": {
                        "description": "Invalid token",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/users/favorites/{dish_id}": {
            "delete": {
                "description": "Extract the user session from the provided token, validate the dish ID (UUIDv4),\nthen remove the dish from the user’s favorites list.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "/users/favorites"
                ],
                "summary": "remove_favorite",
                "parameters": [
                    {
                        "type": "string",
                        "description": "256-bit random session token",
                        "name": "Token",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "UUIDv4 dish identifier",
                        "name": "dish_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "removed dish id",
                        "schema": {
                            "$ref": "#/definitions/handlers.RemoveFavoriteResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid id",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "401": {
                        "description": "no auth token found",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "403": {
                        "description": "Invalid token",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "patch": {
                "description": "Extract the user session from the provided token, validate the dish ID (UUIDv4),\nthen insert the dish into the user’s favorites list.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "/users/favorites"
                ],
                "summary": "add_favorite",
                "parameters": [
                    {
                        "type": "string",
                        "description": "256-bit random session token",
                        "name": "Token",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "UUIDv4 dish identifier",
                        "name": "dish_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Added to favorites",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Invalid id",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "401": {
                        "description": "no auth token found",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "403": {
                        "description": "Invalid token",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/users/information": {
            "get": {
                "description": "Get the user id from the received session token, then query and return with the corresponding user’s information (except password)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "/users/information"
                ],
                "summary": "get_info",
                "parameters": [
                    {
                        "type": "string",
                        "example": "f3d9c4e6a7b1ce204fa8d5b39e181f9b3e2c1d7fbe4490d6732eab5c4fd7c92e",
                        "description": "256bit random token",
                        "name": "Token",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Ok",
                        "schema": {
                            "$ref": "#/definitions/handlers.GetUserResponse"
                        }
                    },
                    "401": {
                        "description": "no auth token found",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "403": {
                        "description": "Invalid token",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "patch": {
                "description": "Get the user id from the received session token, then query and return with the corresponding user’s information (except password)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "/users/information"
                ],
                "summary": "edit_info",
                "parameters": [
                    {
                        "type": "string",
                        "description": "256bit random token",
                        "name": "Token",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "new info",
                        "name": "Input",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/users.EditUserParam"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Ok",
                        "schema": {
                            "$ref": "#/definitions/handlers.EditUserResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid input",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "401": {
                        "description": "no auth token found",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "403": {
                        "description": "Invalid token",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/users/password": {
            "patch": {
                "description": "Extracts the user session from the provided token, validates the request body,\nthen updates the user's password.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "/users/password"
                ],
                "summary": "change_password",
                "parameters": [
                    {
                        "type": "string",
                        "description": "256-bit random session token",
                        "name": "Token",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "New password payload",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/users.ChangePasswordParam"
                        }
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "Invalid Body",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "401": {
                        "description": "No auth token found",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "403": {
                        "description": "Invalid token",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "auth.LoginParam": {
            "type": "object",
            "properties": {
                "password": {
                    "type": "string",
                    "example": "11111"
                },
                "username": {
                    "type": "string",
                    "example": "ranto"
                }
            }
        },
        "auth.LoginResponse": {
            "type": "object",
            "properties": {
                "token": {
                    "type": "string",
                    "example": "f3d1b8cd4f29e6a173c0dd9d84b3af2d2e19a74ccf8b0e57a3c4d90e8f12b7ac"
                }
            }
        },
        "auth.SignupParam": {
            "type": "object",
            "properties": {
                "display_name": {
                    "type": "string",
                    "example": "phantom"
                },
                "email": {
                    "type": "string",
                    "example": "ranto@example.com"
                },
                "password": {
                    "type": "string",
                    "example": "1233445"
                },
                "username": {
                    "type": "string",
                    "example": "ranto"
                }
            }
        },
        "auth.SignupResponse": {
            "type": "object",
            "properties": {
                "token": {
                    "type": "string",
                    "example": "f3d1b8cd4f29e6a173c0dd9d84b3af2d2e19a74ccf8b0e57a3c4d90e8f12b7ac"
                }
            }
        },
        "dishes.DishResult": {
            "type": "object",
            "properties": {
                "altName": {
                    "type": "string"
                },
                "course": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "dishID": {
                    "type": "string"
                },
                "dishName": {
                    "type": "string"
                }
            }
        },
        "handlers.EditUserResponse": {
            "type": "object",
            "properties": {
                "display_name": {
                    "type": "string",
                    "example": "phantom_1234"
                },
                "email": {
                    "type": "string",
                    "example": "ranto@example.com"
                }
            }
        },
        "handlers.Favorites": {
            "type": "object",
            "properties": {
                "dish_id": {
                    "type": "string"
                },
                "dish_name": {
                    "type": "string"
                }
            }
        },
        "handlers.GetUserResponse": {
            "type": "object",
            "properties": {
                "display_name": {
                    "type": "string",
                    "example": "phantom_1234"
                },
                "email": {
                    "type": "string",
                    "example": "ranto@example.com"
                },
                "username": {
                    "type": "string",
                    "example": "ranto"
                }
            }
        },
        "handlers.RemoveFavoriteResponse": {
            "type": "object",
            "properties": {
                "dish_id": {
                    "type": "string",
                    "example": "123e4567-e89b-12d3-a456-426614174000"
                }
            }
        },
        "handlers.SearchDishesResponse": {
            "type": "object",
            "properties": {
                "dishes": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dishes.DishResult"
                    }
                },
                "limit": {
                    "type": "integer"
                },
                "page": {
                    "type": "integer"
                },
                "total_pages": {
                    "type": "integer"
                },
                "total_results": {
                    "type": "integer"
                }
            }
        },
        "users.ChangePasswordParam": {
            "type": "object",
            "properties": {
                "current_password": {
                    "type": "string"
                },
                "new_password": {
                    "type": "string"
                }
            }
        },
        "users.EditUserParam": {
            "type": "object",
            "properties": {
                "display_name": {
                    "type": "string",
                    "example": "phantom_1234"
                },
                "email": {
                    "type": "string",
                    "example": "ranto@example.com"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "Macro_vision backend",
	Description:      "API for Macro_vision",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
