// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package database

import (
	"database/sql"
	"time"
)

type Dish struct {
	ID          int64
	Name        string
	Course      string
	AltName     sql.NullString
	FullRecipe  string
	Source      string
	Description string
}

type DishIngredient struct {
	DishID       string
	IngredientID string
	Amount       string
	Unit         string
}

type Ingredient struct {
	ID          int64
	Name        string
	Description string
}

type IngredientMacro struct {
	IngredientID int64
	PerGrams     float64
	Calories     float64
	Protein      float64
	Fat          float64
	Carbs        float64
	Fiber        float64
}

type Session struct {
	ID          int64
	Username    string
	Token       string
	ExpiresAt   time.Time
	DateCreated time.Time
}
