// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: queries.sql

package database

import (
	"context"
)

const test = `-- name: test :exec
select id, name, course, alt_name, full_recipe, source, description
from dishes
`

func (q *Queries) test(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, test)
	return err
}
