// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: recipe_queries.sql

package database

import (
	"context"
)

const test_recipes = `-- name: test_recipes :exec
select id, name, course, alt_name, full_recipe, source, description
from dishes
`

func (q *Queries) test_recipes(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, test_recipes)
	return err
}
