// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package database

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type DbInfo struct {
	Version     uuid.UUID
	LastScraped time.Time
}

type Dish struct {
	DishID      uuid.UUID
	DishName    string
	Course      string
	AltName     sql.NullString
	FullRecipe  string
	Source      string
	Description string
	DateCreated time.Time
}

type DishIngredient struct {
	DishID       uuid.UUID
	IngredientID uuid.UUID
	Amount       float32
	Unit         string
}

type Favorite struct {
	UserID      uuid.UUID
	DishID      uuid.UUID
	DateCreated time.Time
}

type Ingredient struct {
	IngredientID   uuid.UUID
	IngredientName string
	DateCreated    time.Time
}

type MealCard struct {
	CardID      uuid.UUID
	UserID      uuid.UUID
	Title       string
	MealDate    time.Time
	DateCreated time.Time
}

type MealCardsDish struct {
	CardID uuid.UUID
	DishID uuid.UUID
}

type Session struct {
	SessionID   uuid.UUID
	UserID      uuid.UUID
	Token       string
	ExpiresAt   time.Time
	DateCreated time.Time
}

type User struct {
	UserID       uuid.UUID
	Username     string
	DisplayName  string
	Email        string
	PasswordHash string
	DateCreated  time.Time
}
