// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: queries.sql

package database

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
	"github.com/lib/pq"
)

const add_dish_to_card = `-- name: Add_dish_to_card :one
insert into meal_cards_dishes(card_id, dish_id)
values($1, $2)
on conflict do nothing
returning card_id
`

type Add_dish_to_cardParams struct {
	CardID uuid.UUID `json:"card_id"`
	DishID uuid.UUID `json:"dish_id"`
}

func (q *Queries) Add_dish_to_card(ctx context.Context, arg Add_dish_to_cardParams) (uuid.UUID, error) {
	row := q.db.QueryRowContext(ctx, add_dish_to_card, arg.CardID, arg.DishID)
	var card_id uuid.UUID
	err := row.Scan(&card_id)
	return card_id, err
}

const add_dishes_to_card = `-- name: Add_dishes_to_card :exec
INSERT INTO meal_cards_dishes (card_id, dish_id)
SELECT
    $1,
    unnest($2::uuid[])
ON CONFLICT DO NOTHING
`

type Add_dishes_to_cardParams struct {
	CardID  uuid.UUID   `json:"card_id"`
	Column2 []uuid.UUID `json:"column_2"`
}

func (q *Queries) Add_dishes_to_card(ctx context.Context, arg Add_dishes_to_cardParams) error {
	_, err := q.db.ExecContext(ctx, add_dishes_to_card, arg.CardID, pq.Array(arg.Column2))
	return err
}

const add_favorites = `-- name: Add_favorites :one
insert into favorites(
    user_id,
    dish_id,
    date_created
)
values($1,$2,$3)
returning dish_id
`

type Add_favoritesParams struct {
	UserID      uuid.UUID `json:"user_id"`
	DishID      uuid.UUID `json:"dish_id"`
	DateCreated time.Time `json:"date_created"`
}

func (q *Queries) Add_favorites(ctx context.Context, arg Add_favoritesParams) (uuid.UUID, error) {
	row := q.db.QueryRowContext(ctx, add_favorites, arg.UserID, arg.DishID, arg.DateCreated)
	var dish_id uuid.UUID
	err := row.Scan(&dish_id)
	return dish_id, err
}

const change_password = `-- name: Change_password :exec
update users
set password_hash=$2
where user_id=$1
`

type Change_passwordParams struct {
	UserID       uuid.UUID `json:"user_id"`
	PasswordHash string    `json:"password_hash"`
}

func (q *Queries) Change_password(ctx context.Context, arg Change_passwordParams) error {
	_, err := q.db.ExecContext(ctx, change_password, arg.UserID, arg.PasswordHash)
	return err
}

const create_meal_card = `-- name: Create_meal_card :one
insert into meal_cards(
    card_id,
    user_id,
    title,
    meal_date,
    date_created
)
values($1, $2, $3, $4, $5)
returning card_id, user_id, title, meal_date, date_created
`

type Create_meal_cardParams struct {
	CardID      uuid.UUID `json:"card_id"`
	UserID      uuid.UUID `json:"user_id"`
	Title       string    `json:"title"`
	MealDate    time.Time `json:"meal_date"`
	DateCreated time.Time `json:"date_created"`
}

func (q *Queries) Create_meal_card(ctx context.Context, arg Create_meal_cardParams) (MealCard, error) {
	row := q.db.QueryRowContext(ctx, create_meal_card,
		arg.CardID,
		arg.UserID,
		arg.Title,
		arg.MealDate,
		arg.DateCreated,
	)
	var i MealCard
	err := row.Scan(
		&i.CardID,
		&i.UserID,
		&i.Title,
		&i.MealDate,
		&i.DateCreated,
	)
	return i, err
}

const edit_user = `-- name: Edit_user :one
update users
set display_name=$2, email=$3
where user_id=$1
returning display_name, email
`

type Edit_userParams struct {
	UserID      uuid.UUID `json:"user_id"`
	DisplayName string    `json:"display_name"`
	Email       string    `json:"email"`
}

type Edit_userRow struct {
	DisplayName string `json:"display_name"`
	Email       string `json:"email"`
}

func (q *Queries) Edit_user(ctx context.Context, arg Edit_userParams) (Edit_userRow, error) {
	row := q.db.QueryRowContext(ctx, edit_user, arg.UserID, arg.DisplayName, arg.Email)
	var i Edit_userRow
	err := row.Scan(&i.DisplayName, &i.Email)
	return i, err
}

const getInfo = `-- name: GetInfo :one
select version, last_scraped
from db_info
`

// ============ DB INFO
func (q *Queries) GetInfo(ctx context.Context) (DbInfo, error) {
	row := q.db.QueryRowContext(ctx, getInfo)
	var i DbInfo
	err := row.Scan(&i.Version, &i.LastScraped)
	return i, err
}

const get_all_dishes = `-- name: Get_all_dishes :many
select dish_id, dish_name, course, alt_name, full_recipe, source, description, date_created
from dishes
`

// ============ Main_dishes
func (q *Queries) Get_all_dishes(ctx context.Context) ([]Dish, error) {
	rows, err := q.db.QueryContext(ctx, get_all_dishes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Dish
	for rows.Next() {
		var i Dish
		if err := rows.Scan(
			&i.DishID,
			&i.DishName,
			&i.Course,
			&i.AltName,
			&i.FullRecipe,
			&i.Source,
			&i.Description,
			&i.DateCreated,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const get_all_ingredients = `-- name: Get_all_ingredients :many
select ingredient_id, ingredient_name, date_created from ingredients
`

// ============ Ingredients
func (q *Queries) Get_all_ingredients(ctx context.Context) ([]Ingredient, error) {
	rows, err := q.db.QueryContext(ctx, get_all_ingredients)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Ingredient
	for rows.Next() {
		var i Ingredient
		if err := rows.Scan(&i.IngredientID, &i.IngredientName, &i.DateCreated); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const get_card_with_id = `-- name: Get_card_with_id :one
select card_id, user_id, title, meal_date, date_created from meal_cards
where card_id = $1 and user_id=$2
`

type Get_card_with_idParams struct {
	CardID uuid.UUID `json:"card_id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) Get_card_with_id(ctx context.Context, arg Get_card_with_idParams) (MealCard, error) {
	row := q.db.QueryRowContext(ctx, get_card_with_id, arg.CardID, arg.UserID)
	var i MealCard
	err := row.Scan(
		&i.CardID,
		&i.UserID,
		&i.Title,
		&i.MealDate,
		&i.DateCreated,
	)
	return i, err
}

const get_dish = `-- name: Get_dish :one
select dish_id, dish_name, course, alt_name, full_recipe, source, description, date_created from dishes
where dish_id = $1
`

func (q *Queries) Get_dish(ctx context.Context, dishID uuid.UUID) (Dish, error) {
	row := q.db.QueryRowContext(ctx, get_dish, dishID)
	var i Dish
	err := row.Scan(
		&i.DishID,
		&i.DishName,
		&i.Course,
		&i.AltName,
		&i.FullRecipe,
		&i.Source,
		&i.Description,
		&i.DateCreated,
	)
	return i, err
}

const get_dishes_in_meal_card = `-- name: Get_dishes_in_meal_card :many
select d.dish_id, dish_name, course, alt_name, full_recipe, source, description, date_created, card_id, mcd.dish_id
from dishes d
join meal_cards_dishes mcd on mcd.dish_id = d.dish_id
where mcd.card_id = $1
`

type Get_dishes_in_meal_cardRow struct {
	DishID      uuid.UUID      `json:"dish_id"`
	DishName    string         `json:"dish_name"`
	Course      string         `json:"course"`
	AltName     sql.NullString `json:"alt_name"`
	FullRecipe  string         `json:"full_recipe"`
	Source      string         `json:"source"`
	Description string         `json:"description"`
	DateCreated time.Time      `json:"date_created"`
	CardID      uuid.UUID      `json:"card_id"`
	DishID_2    uuid.UUID      `json:"dish_id_2"`
}

func (q *Queries) Get_dishes_in_meal_card(ctx context.Context, cardID uuid.UUID) ([]Get_dishes_in_meal_cardRow, error) {
	rows, err := q.db.QueryContext(ctx, get_dishes_in_meal_card, cardID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Get_dishes_in_meal_cardRow
	for rows.Next() {
		var i Get_dishes_in_meal_cardRow
		if err := rows.Scan(
			&i.DishID,
			&i.DishName,
			&i.Course,
			&i.AltName,
			&i.FullRecipe,
			&i.Source,
			&i.Description,
			&i.DateCreated,
			&i.CardID,
			&i.DishID_2,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const get_favorites = `-- name: Get_favorites :many
select dishes.dish_id, dishes.dish_name from dishes
inner join favorites on favorites.dish_id = dishes.dish_id
where favorites.user_id = $1
`

type Get_favoritesRow struct {
	DishID   uuid.UUID `json:"dish_id"`
	DishName string    `json:"dish_name"`
}

func (q *Queries) Get_favorites(ctx context.Context, userID uuid.UUID) ([]Get_favoritesRow, error) {
	rows, err := q.db.QueryContext(ctx, get_favorites, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Get_favoritesRow
	for rows.Next() {
		var i Get_favoritesRow
		if err := rows.Scan(&i.DishID, &i.DishName); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const get_meal_cards_daily = `-- name: Get_meal_cards_daily :many

select card_id, user_id, title, meal_date, date_created from meal_cards
WHERE meal_date >= $1
  AND meal_date <  $1 + INTERVAL '1 day'
  and user_id=$2
`

type Get_meal_cards_dailyParams struct {
	MealDate time.Time `json:"meal_date"`
	UserID   uuid.UUID `json:"user_id"`
}

// Meal cards --
func (q *Queries) Get_meal_cards_daily(ctx context.Context, arg Get_meal_cards_dailyParams) ([]MealCard, error) {
	rows, err := q.db.QueryContext(ctx, get_meal_cards_daily, arg.MealDate, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MealCard
	for rows.Next() {
		var i MealCard
		if err := rows.Scan(
			&i.CardID,
			&i.UserID,
			&i.Title,
			&i.MealDate,
			&i.DateCreated,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const get_meal_cards_monthly = `-- name: Get_meal_cards_monthly :many
SELECT card_id, user_id, title, meal_date, date_created
FROM meal_cards
WHERE meal_date >= date_trunc('month', $1::timestamptz)
  AND meal_date <  date_trunc('month', $1::timestamptz) + INTERVAL '1 month'
  and user_id=$2
`

type Get_meal_cards_monthlyParams struct {
	Column1 time.Time `json:"column_1"`
	UserID  uuid.UUID `json:"user_id"`
}

func (q *Queries) Get_meal_cards_monthly(ctx context.Context, arg Get_meal_cards_monthlyParams) ([]MealCard, error) {
	rows, err := q.db.QueryContext(ctx, get_meal_cards_monthly, arg.Column1, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MealCard
	for rows.Next() {
		var i MealCard
		if err := rows.Scan(
			&i.CardID,
			&i.UserID,
			&i.Title,
			&i.MealDate,
			&i.DateCreated,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const get_one_ingredient = `-- name: Get_one_ingredient :one
select ingredient_id, ingredient_name, date_created from ingredients
where ingredient_id = $1
`

func (q *Queries) Get_one_ingredient(ctx context.Context, ingredientID uuid.UUID) (Ingredient, error) {
	row := q.db.QueryRowContext(ctx, get_one_ingredient, ingredientID)
	var i Ingredient
	err := row.Scan(&i.IngredientID, &i.IngredientName, &i.DateCreated)
	return i, err
}

const get_session = `-- name: Get_session :one
select session_id, user_id, token, expires_at, date_created
from sessions
where token = $1
`

// ----SESSION-----
func (q *Queries) Get_session(ctx context.Context, token string) (Session, error) {
	row := q.db.QueryRowContext(ctx, get_session, token)
	var i Session
	err := row.Scan(
		&i.SessionID,
		&i.UserID,
		&i.Token,
		&i.ExpiresAt,
		&i.DateCreated,
	)
	return i, err
}

const get_token = `-- name: Get_token :one
select token
from sessions
where session_id = $1
`

func (q *Queries) Get_token(ctx context.Context, sessionID uuid.UUID) (string, error) {
	row := q.db.QueryRowContext(ctx, get_token, sessionID)
	var token string
	err := row.Scan(&token)
	return token, err
}

const get_user_from_id = `-- name: Get_user_from_id :one
select user_id, username, display_name, email, password_hash, date_created
from users
where user_id = $1
`

func (q *Queries) Get_user_from_id(ctx context.Context, userID uuid.UUID) (User, error) {
	row := q.db.QueryRowContext(ctx, get_user_from_id, userID)
	var i User
	err := row.Scan(
		&i.UserID,
		&i.Username,
		&i.DisplayName,
		&i.Email,
		&i.PasswordHash,
		&i.DateCreated,
	)
	return i, err
}

const get_user_from_name = `-- name: Get_user_from_name :one
select user_id, username, display_name, email, password_hash, date_created
from users
where username = $1
`

func (q *Queries) Get_user_from_name(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRowContext(ctx, get_user_from_name, username)
	var i User
	err := row.Scan(
		&i.UserID,
		&i.Username,
		&i.DisplayName,
		&i.Email,
		&i.PasswordHash,
		&i.DateCreated,
	)
	return i, err
}

const get_user_from_token = `-- name: Get_user_from_token :one
select users.user_id, users.username, users.display_name, users.email, users.password_hash, users.date_created
from sessions
join users on users.user_id = sessions.user_id
where sessions.token = $1
and sessions.expires_at > NOW()
`

// ----users-----
func (q *Queries) Get_user_from_token(ctx context.Context, token string) (User, error) {
	row := q.db.QueryRowContext(ctx, get_user_from_token, token)
	var i User
	err := row.Scan(
		&i.UserID,
		&i.Username,
		&i.DisplayName,
		&i.Email,
		&i.PasswordHash,
		&i.DateCreated,
	)
	return i, err
}

const insert_dish = `-- name: Insert_dish :one
INSERT INTO dishes(
	dish_id,
	dish_name,
	course,
	alt_name,
	full_recipe,
	source,
	description,
	date_created
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING dish_id
`

type Insert_dishParams struct {
	DishID      uuid.UUID      `json:"dish_id"`
	DishName    string         `json:"dish_name"`
	Course      string         `json:"course"`
	AltName     sql.NullString `json:"alt_name"`
	FullRecipe  string         `json:"full_recipe"`
	Source      string         `json:"source"`
	Description string         `json:"description"`
	DateCreated time.Time      `json:"date_created"`
}

func (q *Queries) Insert_dish(ctx context.Context, arg Insert_dishParams) (uuid.UUID, error) {
	row := q.db.QueryRowContext(ctx, insert_dish,
		arg.DishID,
		arg.DishName,
		arg.Course,
		arg.AltName,
		arg.FullRecipe,
		arg.Source,
		arg.Description,
		arg.DateCreated,
	)
	var dish_id uuid.UUID
	err := row.Scan(&dish_id)
	return dish_id, err
}

const insert_dish_ingredients = `-- name: Insert_dish_ingredients :exec
INSERT INTO dish_ingredients(
	dish_id,
	ingredient_id,
	amount,
	unit
)
VALUES ($1, $2, $3, $4)
`

type Insert_dish_ingredientsParams struct {
	DishID       uuid.UUID `json:"dish_id"`
	IngredientID uuid.UUID `json:"ingredient_id"`
	Amount       float32   `json:"amount"`
	Unit         string    `json:"unit"`
}

func (q *Queries) Insert_dish_ingredients(ctx context.Context, arg Insert_dish_ingredientsParams) error {
	_, err := q.db.ExecContext(ctx, insert_dish_ingredients,
		arg.DishID,
		arg.IngredientID,
		arg.Amount,
		arg.Unit,
	)
	return err
}

const insert_session = `-- name: Insert_session :exec
INSERT INTO sessions(
	session_id,
	user_id,
	token,
	expires_at,
	date_created
)
VALUES ($1, $2, $3, $4, $5)
`

type Insert_sessionParams struct {
	SessionID   uuid.UUID `json:"session_id"`
	UserID      uuid.UUID `json:"user_id"`
	Token       string    `json:"token"`
	ExpiresAt   time.Time `json:"expires_at"`
	DateCreated time.Time `json:"date_created"`
}

func (q *Queries) Insert_session(ctx context.Context, arg Insert_sessionParams) error {
	_, err := q.db.ExecContext(ctx, insert_session,
		arg.SessionID,
		arg.UserID,
		arg.Token,
		arg.ExpiresAt,
		arg.DateCreated,
	)
	return err
}

const insert_user = `-- name: Insert_user :one
INSERT INTO users(
	user_id,
	username,
	display_name,
	email,
	password_hash,
	date_created
)
VALUES ($1, $2, $3, $4, $5, $6)
returning user_id
`

type Insert_userParams struct {
	UserID       uuid.UUID `json:"user_id"`
	Username     string    `json:"username"`
	DisplayName  string    `json:"display_name"`
	Email        string    `json:"email"`
	PasswordHash string    `json:"password_hash"`
	DateCreated  time.Time `json:"date_created"`
}

func (q *Queries) Insert_user(ctx context.Context, arg Insert_userParams) (uuid.UUID, error) {
	row := q.db.QueryRowContext(ctx, insert_user,
		arg.UserID,
		arg.Username,
		arg.DisplayName,
		arg.Email,
		arg.PasswordHash,
		arg.DateCreated,
	)
	var user_id uuid.UUID
	err := row.Scan(&user_id)
	return user_id, err
}

const remove_card = `-- name: Remove_card :one
delete from meal_cards
where card_id = $1 and user_id = $2
returning card_id
`

type Remove_cardParams struct {
	CardID uuid.UUID `json:"card_id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) Remove_card(ctx context.Context, arg Remove_cardParams) (uuid.UUID, error) {
	row := q.db.QueryRowContext(ctx, remove_card, arg.CardID, arg.UserID)
	var card_id uuid.UUID
	err := row.Scan(&card_id)
	return card_id, err
}

const remove_dish_from_card = `-- name: Remove_dish_from_card :one
delete from meal_cards_dishes
where card_id=$1 and dish_id=$2
returning card_id
`

type Remove_dish_from_cardParams struct {
	CardID uuid.UUID `json:"card_id"`
	DishID uuid.UUID `json:"dish_id"`
}

func (q *Queries) Remove_dish_from_card(ctx context.Context, arg Remove_dish_from_cardParams) (uuid.UUID, error) {
	row := q.db.QueryRowContext(ctx, remove_dish_from_card, arg.CardID, arg.DishID)
	var card_id uuid.UUID
	err := row.Scan(&card_id)
	return card_id, err
}

const remove_favorite = `-- name: Remove_favorite :one
DELETE FROM favorites
WHERE user_id = $1 AND dish_id = $2
returning dish_id
`

type Remove_favoriteParams struct {
	UserID uuid.UUID `json:"user_id"`
	DishID uuid.UUID `json:"dish_id"`
}

func (q *Queries) Remove_favorite(ctx context.Context, arg Remove_favoriteParams) (uuid.UUID, error) {
	row := q.db.QueryRowContext(ctx, remove_favorite, arg.UserID, arg.DishID)
	var dish_id uuid.UUID
	err := row.Scan(&dish_id)
	return dish_id, err
}

const remove_session = `-- name: Remove_session :exec
delete from sessions
where token = $1
`

func (q *Queries) Remove_session(ctx context.Context, token string) error {
	_, err := q.db.ExecContext(ctx, remove_session, token)
	return err
}

const search_dishes = `-- name: Search_dishes :many

SELECT
    d.dish_id,
    d.dish_name,
    d.course,
    COALESCE(d.alt_name, '') AS alt_name,
    d.description,
    COUNT(*) OVER () AS matches
FROM dishes d
JOIN dish_ingredients di
    ON di.dish_id = d.dish_id
WHERE
    d.dish_name ILIKE $1
    AND d.course = ANY($2::text[])
GROUP BY
    d.dish_id
HAVING
    COUNT(di.ingredient_id)

BETWEEN $3::int AND $4::int
LIMIT $6::int offset $5::int
`

type Search_dishesParams struct {
	Query          string   `json:"query"`
	Courses        []string `json:"courses"`
	MinIngredients int32    `json:"min_ingredients"`
	MaxIngredients int32    `json:"max_ingredients"`
	OffsetValue    int32    `json:"offset_value"`
	ReturnLimit    int32    `json:"return_limit"`
}

type Search_dishesRow struct {
	DishID      uuid.UUID `json:"dish_id"`
	DishName    string    `json:"dish_name"`
	Course      string    `json:"course"`
	AltName     string    `json:"alt_name"`
	Description string    `json:"description"`
	Matches     int64     `json:"matches"`
}

// DISHES --
func (q *Queries) Search_dishes(ctx context.Context, arg Search_dishesParams) ([]Search_dishesRow, error) {
	rows, err := q.db.QueryContext(ctx, search_dishes,
		arg.Query,
		pq.Array(arg.Courses),
		arg.MinIngredients,
		arg.MaxIngredients,
		arg.OffsetValue,
		arg.ReturnLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Search_dishesRow
	for rows.Next() {
		var i Search_dishesRow
		if err := rows.Scan(
			&i.DishID,
			&i.DishName,
			&i.Course,
			&i.AltName,
			&i.Description,
			&i.Matches,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const search_ingredients = `-- name: Search_ingredients :many
select ingredient_id, ingredient_name, date_created from ingredients
where ingredient_name ILIKE $1
`

func (q *Queries) Search_ingredients(ctx context.Context, ingredientName string) ([]Ingredient, error) {
	rows, err := q.db.QueryContext(ctx, search_ingredients, ingredientName)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Ingredient
	for rows.Next() {
		var i Ingredient
		if err := rows.Scan(&i.IngredientID, &i.IngredientName, &i.DateCreated); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateInfo = `-- name: UpdateInfo :exec
INSERT INTO db_info (version, last_scraped)
VALUES ($1, $2)
ON CONFLICT (version)
DO UPDATE SET
    version = EXCLUDED.version,
    last_scraped = EXCLUDED.last_scraped
`

type UpdateInfoParams struct {
	Version     uuid.UUID `json:"version"`
	LastScraped time.Time `json:"last_scraped"`
}

func (q *Queries) UpdateInfo(ctx context.Context, arg UpdateInfoParams) error {
	_, err := q.db.ExecContext(ctx, updateInfo, arg.Version, arg.LastScraped)
	return err
}

const update_meal_card_info = `-- name: Update_meal_card_info :one
update meal_cards
set title= $3, meal_date=$4
where card_id=$1 and user_id=$2
returning card_id, user_id, title, meal_date, date_created
`

type Update_meal_card_infoParams struct {
	CardID   uuid.UUID `json:"card_id"`
	UserID   uuid.UUID `json:"user_id"`
	Title    string    `json:"title"`
	MealDate time.Time `json:"meal_date"`
}

func (q *Queries) Update_meal_card_info(ctx context.Context, arg Update_meal_card_infoParams) (MealCard, error) {
	row := q.db.QueryRowContext(ctx, update_meal_card_info,
		arg.CardID,
		arg.UserID,
		arg.Title,
		arg.MealDate,
	)
	var i MealCard
	err := row.Scan(
		&i.CardID,
		&i.UserID,
		&i.Title,
		&i.MealDate,
		&i.DateCreated,
	)
	return i, err
}

const upsert_ingredient = `-- name: Upsert_ingredient :one
INSERT INTO ingredients(
    ingredient_id, ingredient_name, date_created
)
VALUES ($1, $2, $3)
ON CONFLICT (ingredient_name) DO NOTHING
RETURNING ingredient_id
`

type Upsert_ingredientParams struct {
	IngredientID   uuid.UUID `json:"ingredient_id"`
	IngredientName string    `json:"ingredient_name"`
	DateCreated    time.Time `json:"date_created"`
}

func (q *Queries) Upsert_ingredient(ctx context.Context, arg Upsert_ingredientParams) (uuid.UUID, error) {
	row := q.db.QueryRowContext(ctx, upsert_ingredient, arg.IngredientID, arg.IngredientName, arg.DateCreated)
	var ingredient_id uuid.UUID
	err := row.Scan(&ingredient_id)
	return ingredient_id, err
}
