// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: queries.sql

package database

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const add_favorites = `-- name: Add_favorites :one
insert into favorites(
    user_id,
    dish_id,
    date_created
)
values($1,$2,$3)
returning dish_id
`

type Add_favoritesParams struct {
	UserID      uuid.UUID `json:"user_id"`
	DishID      uuid.UUID `json:"dish_id"`
	DateCreated time.Time `json:"date_created"`
}

func (q *Queries) Add_favorites(ctx context.Context, arg Add_favoritesParams) (uuid.UUID, error) {
	row := q.db.QueryRowContext(ctx, add_favorites, arg.UserID, arg.DishID, arg.DateCreated)
	var dish_id uuid.UUID
	err := row.Scan(&dish_id)
	return dish_id, err
}

const change_password = `-- name: Change_password :exec
update users
set password_hash=$2
where user_id=$1
`

type Change_passwordParams struct {
	UserID       uuid.UUID `json:"user_id"`
	PasswordHash string    `json:"password_hash"`
}

func (q *Queries) Change_password(ctx context.Context, arg Change_passwordParams) error {
	_, err := q.db.ExecContext(ctx, change_password, arg.UserID, arg.PasswordHash)
	return err
}

const edit_user = `-- name: Edit_user :one
update users
set display_name=$2, email=$3
where user_id=$1
returning display_name, email
`

type Edit_userParams struct {
	UserID      uuid.UUID `json:"user_id"`
	DisplayName string    `json:"display_name"`
	Email       string    `json:"email"`
}

type Edit_userRow struct {
	DisplayName string `json:"display_name"`
	Email       string `json:"email"`
}

func (q *Queries) Edit_user(ctx context.Context, arg Edit_userParams) (Edit_userRow, error) {
	row := q.db.QueryRowContext(ctx, edit_user, arg.UserID, arg.DisplayName, arg.Email)
	var i Edit_userRow
	err := row.Scan(&i.DisplayName, &i.Email)
	return i, err
}

const getInfo = `-- name: GetInfo :one
select version, last_scraped
from db_info
`

// ============ DB INFO
func (q *Queries) GetInfo(ctx context.Context) (DbInfo, error) {
	row := q.db.QueryRowContext(ctx, getInfo)
	var i DbInfo
	err := row.Scan(&i.Version, &i.LastScraped)
	return i, err
}

const get_all_dishes = `-- name: Get_all_dishes :many
select dish_id, dish_name, course, alt_name, full_recipe, source, description, date_created
from dishes
`

// ============ Main_dishes
func (q *Queries) Get_all_dishes(ctx context.Context) ([]Dish, error) {
	rows, err := q.db.QueryContext(ctx, get_all_dishes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Dish
	for rows.Next() {
		var i Dish
		if err := rows.Scan(
			&i.DishID,
			&i.DishName,
			&i.Course,
			&i.AltName,
			&i.FullRecipe,
			&i.Source,
			&i.Description,
			&i.DateCreated,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const get_favorites = `-- name: Get_favorites :many
select dishes.dish_id, dishes.dish_name from dishes
inner join favorites on favorites.dish_id = dishes.dish_id
where favorites.user_id = $1
`

type Get_favoritesRow struct {
	DishID   uuid.UUID `json:"dish_id"`
	DishName string    `json:"dish_name"`
}

func (q *Queries) Get_favorites(ctx context.Context, userID uuid.UUID) ([]Get_favoritesRow, error) {
	rows, err := q.db.QueryContext(ctx, get_favorites, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Get_favoritesRow
	for rows.Next() {
		var i Get_favoritesRow
		if err := rows.Scan(&i.DishID, &i.DishName); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const get_session = `-- name: Get_session :one
select session_id, user_id, token, expires_at, date_created
from sessions
where token = $1
`

// ----SESSION-----
func (q *Queries) Get_session(ctx context.Context, token string) (Session, error) {
	row := q.db.QueryRowContext(ctx, get_session, token)
	var i Session
	err := row.Scan(
		&i.SessionID,
		&i.UserID,
		&i.Token,
		&i.ExpiresAt,
		&i.DateCreated,
	)
	return i, err
}

const get_token = `-- name: Get_token :one
select token
from sessions
where session_id = $1
`

func (q *Queries) Get_token(ctx context.Context, sessionID uuid.UUID) (string, error) {
	row := q.db.QueryRowContext(ctx, get_token, sessionID)
	var token string
	err := row.Scan(&token)
	return token, err
}

const get_user_from_id = `-- name: Get_user_from_id :one
select user_id, username, display_name, email, password_hash, date_created
from users
where user_id = $1
`

func (q *Queries) Get_user_from_id(ctx context.Context, userID uuid.UUID) (User, error) {
	row := q.db.QueryRowContext(ctx, get_user_from_id, userID)
	var i User
	err := row.Scan(
		&i.UserID,
		&i.Username,
		&i.DisplayName,
		&i.Email,
		&i.PasswordHash,
		&i.DateCreated,
	)
	return i, err
}

const get_user_from_name = `-- name: Get_user_from_name :one
select user_id, username, display_name, email, password_hash, date_created
from users
where username = $1
`

func (q *Queries) Get_user_from_name(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRowContext(ctx, get_user_from_name, username)
	var i User
	err := row.Scan(
		&i.UserID,
		&i.Username,
		&i.DisplayName,
		&i.Email,
		&i.PasswordHash,
		&i.DateCreated,
	)
	return i, err
}

const get_user_from_token = `-- name: Get_user_from_token :one
select users.user_id, users.username, users.display_name, users.email, users.password_hash, users.date_created
from sessions
join users on users.user_id = sessions.user_id
where sessions.token = $1
and sessions.expires_at > NOW()
`

// ----users-----
func (q *Queries) Get_user_from_token(ctx context.Context, token string) (User, error) {
	row := q.db.QueryRowContext(ctx, get_user_from_token, token)
	var i User
	err := row.Scan(
		&i.UserID,
		&i.Username,
		&i.DisplayName,
		&i.Email,
		&i.PasswordHash,
		&i.DateCreated,
	)
	return i, err
}

const insert_dish = `-- name: Insert_dish :one
INSERT INTO dishes(
	dish_id,
	dish_name,
	course,
	alt_name,
	full_recipe,
	source,
	description,
	date_created
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING dish_id
`

type Insert_dishParams struct {
	DishID      uuid.UUID      `json:"dish_id"`
	DishName    string         `json:"dish_name"`
	Course      string         `json:"course"`
	AltName     sql.NullString `json:"alt_name"`
	FullRecipe  string         `json:"full_recipe"`
	Source      string         `json:"source"`
	Description string         `json:"description"`
	DateCreated time.Time      `json:"date_created"`
}

func (q *Queries) Insert_dish(ctx context.Context, arg Insert_dishParams) (uuid.UUID, error) {
	row := q.db.QueryRowContext(ctx, insert_dish,
		arg.DishID,
		arg.DishName,
		arg.Course,
		arg.AltName,
		arg.FullRecipe,
		arg.Source,
		arg.Description,
		arg.DateCreated,
	)
	var dish_id uuid.UUID
	err := row.Scan(&dish_id)
	return dish_id, err
}

const insert_dish_ingredients = `-- name: Insert_dish_ingredients :exec
INSERT INTO dish_ingredients(
	dish_id,
	ingredient_id,
	amount,
	unit
)
VALUES ($1, $2, $3, $4)
`

type Insert_dish_ingredientsParams struct {
	DishID       uuid.UUID `json:"dish_id"`
	IngredientID uuid.UUID `json:"ingredient_id"`
	Amount       float32   `json:"amount"`
	Unit         string    `json:"unit"`
}

func (q *Queries) Insert_dish_ingredients(ctx context.Context, arg Insert_dish_ingredientsParams) error {
	_, err := q.db.ExecContext(ctx, insert_dish_ingredients,
		arg.DishID,
		arg.IngredientID,
		arg.Amount,
		arg.Unit,
	)
	return err
}

const insert_session = `-- name: Insert_session :exec
INSERT INTO sessions(
	session_id,
	user_id,
	token,
	expires_at,
	date_created
)
VALUES ($1, $2, $3, $4, $5)
`

type Insert_sessionParams struct {
	SessionID   uuid.UUID `json:"session_id"`
	UserID      uuid.UUID `json:"user_id"`
	Token       string    `json:"token"`
	ExpiresAt   time.Time `json:"expires_at"`
	DateCreated time.Time `json:"date_created"`
}

func (q *Queries) Insert_session(ctx context.Context, arg Insert_sessionParams) error {
	_, err := q.db.ExecContext(ctx, insert_session,
		arg.SessionID,
		arg.UserID,
		arg.Token,
		arg.ExpiresAt,
		arg.DateCreated,
	)
	return err
}

const insert_user = `-- name: Insert_user :one
INSERT INTO users(
	user_id,
	username,
	display_name,
	email,
	password_hash,
	date_created
)
VALUES ($1, $2, $3, $4, $5, $6)
returning user_id
`

type Insert_userParams struct {
	UserID       uuid.UUID `json:"user_id"`
	Username     string    `json:"username"`
	DisplayName  string    `json:"display_name"`
	Email        string    `json:"email"`
	PasswordHash string    `json:"password_hash"`
	DateCreated  time.Time `json:"date_created"`
}

func (q *Queries) Insert_user(ctx context.Context, arg Insert_userParams) (uuid.UUID, error) {
	row := q.db.QueryRowContext(ctx, insert_user,
		arg.UserID,
		arg.Username,
		arg.DisplayName,
		arg.Email,
		arg.PasswordHash,
		arg.DateCreated,
	)
	var user_id uuid.UUID
	err := row.Scan(&user_id)
	return user_id, err
}

const remove_favorite = `-- name: Remove_favorite :one
DELETE FROM favorites
WHERE user_id = $1 AND dish_id = $2
returning dish_id
`

type Remove_favoriteParams struct {
	UserID uuid.UUID `json:"user_id"`
	DishID uuid.UUID `json:"dish_id"`
}

func (q *Queries) Remove_favorite(ctx context.Context, arg Remove_favoriteParams) (uuid.UUID, error) {
	row := q.db.QueryRowContext(ctx, remove_favorite, arg.UserID, arg.DishID)
	var dish_id uuid.UUID
	err := row.Scan(&dish_id)
	return dish_id, err
}

const remove_session = `-- name: Remove_session :exec
delete from sessions
where token = $1
`

func (q *Queries) Remove_session(ctx context.Context, token string) error {
	_, err := q.db.ExecContext(ctx, remove_session, token)
	return err
}

const updateInfo = `-- name: UpdateInfo :exec
INSERT INTO db_info (version, last_scraped)
VALUES ($1, $2)
ON CONFLICT (version)
DO UPDATE SET
    version = EXCLUDED.version,
    last_scraped = EXCLUDED.last_scraped
`

type UpdateInfoParams struct {
	Version     uuid.UUID `json:"version"`
	LastScraped time.Time `json:"last_scraped"`
}

func (q *Queries) UpdateInfo(ctx context.Context, arg UpdateInfoParams) error {
	_, err := q.db.ExecContext(ctx, updateInfo, arg.Version, arg.LastScraped)
	return err
}

const upsert_ingredient = `-- name: Upsert_ingredient :one
INSERT INTO ingredients(
    ingredient_id, ingredient_name, date_created
)
VALUES ($1, $2, $3)
ON CONFLICT (ingredient_name) DO NOTHING
RETURNING ingredient_id
`

type Upsert_ingredientParams struct {
	IngredientID   uuid.UUID `json:"ingredient_id"`
	IngredientName string    `json:"ingredient_name"`
	DateCreated    time.Time `json:"date_created"`
}

// ============ Ingredients
func (q *Queries) Upsert_ingredient(ctx context.Context, arg Upsert_ingredientParams) (uuid.UUID, error) {
	row := q.db.QueryRowContext(ctx, upsert_ingredient, arg.IngredientID, arg.IngredientName, arg.DateCreated)
	var ingredient_id uuid.UUID
	err := row.Scan(&ingredient_id)
	return ingredient_id, err
}
