// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: recipe_queries.sql

package database

import (
	"context"
	"database/sql"
	"time"
)

const get_all_dishes = `-- name: Get_all_dishes :many
select id, name, course, alt_name, full_recipe, source, description, date_created
from dishes
`

// ============ Main_dishes
func (q *Queries) Get_all_dishes(ctx context.Context) ([]Dish, error) {
	rows, err := q.db.QueryContext(ctx, get_all_dishes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Dish
	for rows.Next() {
		var i Dish
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Course,
			&i.AltName,
			&i.FullRecipe,
			&i.Source,
			&i.Description,
			&i.DateCreated,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insert_dish = `-- name: Insert_dish :one
;

INSERT INTO dishes(
	 name, course, alt_name, full_recipe, source, description, date_created
)
VALUES(?,?,?,?,?,?,?)
RETURNING id
`

type Insert_dishParams struct {
	Name        string
	Course      string
	AltName     sql.NullString
	FullRecipe  string
	Source      string
	Description string
	DateCreated time.Time
}

func (q *Queries) Insert_dish(ctx context.Context, arg Insert_dishParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, insert_dish,
		arg.Name,
		arg.Course,
		arg.AltName,
		arg.FullRecipe,
		arg.Source,
		arg.Description,
		arg.DateCreated,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const insert_dish_ingredients = `-- name: Insert_dish_ingredients :exec
INSERT INTO dish_ingredients(
	dish_id, ingredient_id, amount, unit
)
VALUES(?,?,?,?)
`

type Insert_dish_ingredientsParams struct {
	DishID       int64
	IngredientID int64
	Amount       float64
	Unit         string
}

func (q *Queries) Insert_dish_ingredients(ctx context.Context, arg Insert_dish_ingredientsParams) error {
	_, err := q.db.ExecContext(ctx, insert_dish_ingredients,
		arg.DishID,
		arg.IngredientID,
		arg.Amount,
		arg.Unit,
	)
	return err
}

const upsert_ingredient = `-- name: Upsert_ingredient :one
INSERT INTO ingredients(
	 name, date_created
)
values(?,?)
ON CONFLICT(name) DO NOTHING
RETURNING id
`

type Upsert_ingredientParams struct {
	Name        string
	DateCreated time.Time
}

// ============ Ingredients
func (q *Queries) Upsert_ingredient(ctx context.Context, arg Upsert_ingredientParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, upsert_ingredient, arg.Name, arg.DateCreated)
	var id int64
	err := row.Scan(&id)
	return id, err
}
