name: Test

on:
    push:
        branches:
            - ci-test
permissions:
    id-token: write
    contents: read

jobs:
    create-builder:
        runs-on: ubuntu-latest

        steps:
            - name: credentials
              uses: aws-actions/configure-aws-credentials@v4
              with:
                  role-to-assume: ${{secrets.IAM_ROLE_ARN}}
                  aws-region: ap-south-2

            - name: Verify identity
              run: aws sts get-caller-identity

            - name: Launch builder
              run: |
                  INSTANCE_ID=$(aws ec2 run-instances \
                    --image-id ${{vars.PROJECT_ARM_AMI}} \
                    --instance-type ${{vars.BUILDER_INSTANCE_TYPE}} \
                    --security-group-ids sg-069ae7b2c7616ced2 \
                    --iam-instance-profile Name=ec2-ssm \
                    --tag-specifications 'ResourceType=instance,Tags=[{Key=Name,Value=vision-builder}]' \
                    --block-device-mappings '[
                      {
                        "DeviceName": "/dev/xvda",
                        "Ebs": {
                          "VolumeSize": 40,
                          "VolumeType": "gp3",
                          "Iops": 3000,
                          "Throughput": 125,
                          "DeleteOnTermination": true
                        }
                      }
                    ]' \
                    --query 'Instances[0].InstanceId' \
                    --output text)

                  echo "BUILDER_INSTANCE=$INSTANCE_ID" >> $GITHUB_ENV

            - name: Wait for instance
              run: aws ec2 wait instance-running --instance-ids $BUILDER_INSTANCE

            - name: build model_api image and push
              run: |
                  COMMAND_ID=$(aws ssm send-command \
                    --instance-ids $INSTANCE_ID \
                    --document-name "AWS-RunShellScript" \
                    --parameters 'commands=[
                      "set -e",

                      "echo \"${{ secrets.DOCKERHUB_TOKEN }}\" | docker login -u \"${{ secrets.DOCKERHUB_USERNAME }}\" --password-stdin",

                      "cd macro-vision && \
                       git fetch && \
                       git checkout ci-test && \
                       git pull && \
                       cd model && \
                       docker build -t ${{secrets.DOCKERHUB_USERNAME}}/macro-vision-model-api:arm64-latest . && \
                       docker push ${{secrets.DOCKERHUB_USERNAME}}/macro-vision-model-api:arm64-latest"
                    ]' \
                    --query 'Command.CommandId' \
                    --output text)

                  echo "Command ID: $COMMAND_ID"
                  echo "COMMAND_ID=$COMMAND_ID" >> $GITHUB_ENV

            - name: Wait for SSM to be ready
              run: |
                echo "Waiting for SSM registration..."
            
                for i in {1..30}; do
                  FOUND=$(aws ssm describe-instance-information \
                    --query "InstanceInformationList[?InstanceId=='$INSTANCE_ID'].InstanceId" \
                    --output text)
            
                  if [ "$FOUND" = "$INSTANCE_ID" ]; then
                    echo "SSM is ready!"
                    exit 0
                  fi
            
                  echo "Not ready yet... retrying"
                  sleep 5
                done
            
                echo "SSM did not become ready in time"
                exit 1

            - name: Wait for Builder
              run: |
                  while true; do
                    STATUS=$(aws ssm list-command-invocations \
                      --command-id $COMMAND_ID \
                      --query "CommandInvocations[0].Status" \
                      --output text)

                    echo "Status: $STATUS"

                    if [ "$STATUS" = "Success" ]; then
                      break
                    elif [ "$STATUS" = "Failed" ] || [ "$STATUS" = "Cancelled" ] || [ "$STATUS" = "TimedOut" ]; then
                      echo "Command failed"
                      exit 1
                    fi

                    sleep 3
                  done

            - name: Terminate Builder
              if: always()
              run: aws ec2 terminate-instances --instance-ids $BUILDER_INSTANCE

            - name: Ensure main EC2 exists
              run: |
                  INSTANCE_ID=$(aws ec2 describe-instances \
                    --filters "Name=tag:Name,Values=vision-final" \
                              "Name=instance-state-name,Values=pending,running,stopping,stopped" \
                    --query 'Reservations[0].Instances[0].InstanceId' \
                    --output text)

                  if [ "$INSTANCE_ID" = "None" ] || [ -z "$INSTANCE_ID" ]; then
                    echo "No instance found, creating..."

                    INSTANCE_ID=$(aws ec2 run-instances \
                      --image-id ${{vars.PROJECT_ARM_AMI}} \
                      --instance-type ${{vars.MAIN_INSTANCE_TYPE}} \
                      --security-group-ids sg-069ae7b2c7616ced2 \
                      --iam-instance-profile Name=ec2-ssm \
                      --tag-specifications 'ResourceType=instance,Tags=[{Key=Name,Value=vision-final}]' \
                      --block-device-mappings '[
                        {
                          "DeviceName": "/dev/xvda",
                          "Ebs": {
                            "VolumeSize": 40,
                            "VolumeType": "gp3",
                            "Iops": 3000,
                            "Throughput": 125,
                            "DeleteOnTermination": false
                          }
                        }
                      ]' \
                      --query 'Instances[0].InstanceId' \
                      --output text)

                    echo "Created instance: $INSTANCE_ID"
                  else
                    echo "Found existing instance: $INSTANCE_ID"
                  fi

                  echo "MAIN_INSTANCE=$INSTANCE_ID" >> $GITHUB_ENV

            - name: pull model_api and update
              run: |
                  COMMAND_ID=$(aws ssm send-command \
                    --instance-ids $INSTANCE_ID \
                    --document-name "AWS-RunShellScript" \
                    --parameters 'commands=[
                      "set -e",

                      "echo \"${{ secrets.DOCKERHUB_TOKEN }}\" | docker login -u \"${{ secrets.DOCKERHUB_USERNAME }}\" --password-stdin",

                      "cd macro-vision && \
                       git fetch && \
                       git checkout ci-test && \
                       git pull && \
                       docker compose -f compose.prod.yaml down && \
                       docker compose -f compose.prod.yaml pull && \
                       docker compose -f compose.prod.yaml up -d"
                    ]' \
                    --query 'Command.CommandId' \
                    --output text)

                  echo "Command ID: $COMMAND_ID"
                  echo "COMMAND_ID=$COMMAND_ID" >> $GITHUB_ENV

            - name: Wait for Main
              run: |
                  while true; do
                    STATUS=$(aws ssm list-command-invocations \
                      --command-id $COMMAND_ID \
                      --query "CommandInvocations[0].Status" \
                      --output text)

                    echo "Status: $STATUS"

                    if [ "$STATUS" = "Success" ]; then
                      break
                    elif [ "$STATUS" = "Failed" ] || [ "$STATUS" = "Cancelled" ] || [ "$STATUS" = "TimedOut" ]; then
                      echo "Command failed"
                      exit 1
                    fi

                    sleep 3
                  done

            - name: Get public IP
              run: |
                  IP=$(aws ec2 describe-instances \
                    --instance-ids $MAIN_INSTANCE \
                    --query 'Reservations[0].Instances[0].PublicIpAddress' \
                    --output text)

                  echo "EC2 Public IP: $IP"

            - name: Update Cloudflare DNS
              run: |
                  curl -X PUT "https://api.cloudflare.com/client/v4/zones/${{ secrets.CF_ZONE_ID }}/dns_records/${{ secrets.CF_RECORD_ID }}" \
                    -H "Authorization: Bearer ${{ secrets.CF_API_TOKEN }}" \
                    -H "Content-Type: application/json" \
                    --data '{
                      "type": "A",
                      "name": "vision.endstranding.net",
                      "content": "'"$IP"'",
                      "ttl": 1,
                      "proxied": true
                    }'
